import React from 'react';
import PropTypes from 'prop-types';
import ContentContainer from 'terra-content-container';
import Spacer from 'terra-spacer';
import Header from 'terra-action-header';
import StatusView from 'terra-status-view';
/* TODO: Add imports necessary for Kaiju props added below */
import { injectIntl, intlShape } from 'terra-base';

const propTypes = {
  text: PropTypes.string,
  isLoading: PropTypes.bool,
  isFailed: PropTypes.bool,
  intl: intlShape.isRequired,
};

const NavigationDemoView = (props) => {
  const {
    isLoading,
    isFailed,
    text,
    intl,
  } = props;

  let content;
  if (isLoading) {
    content = null;
  } else if (isFailed) {
    content = <StatusView variant={StatusView.Opts.variants.ERROR} message={intl.formatMessage({ id: 'derp-engine.navigation-demo-failed-to-load' })} isGlyphHidden />;
  } else if (text && text.length > 0) {
    content = <Spacer paddingTop="large+1" paddingBottom="large+1" paddingLeft="large+1" paddingRight="large+1">{text}</Spacer>;
  } else {
    content = <StatusView variant={StatusView.Opts.variants.NODATA} message={intl.formatMessage({ id: 'derp-engine.no-navigation-demo' })} isGlyphHidden />;
  }

  return (
    <ContentContainer header={<Header title={intl.formatMessage({ id: 'derp-engine.navigation-demo' })} />}>
      {/* TODO: Add UI props generated by https://kaiju.cerner.com */}
      {content}
    </ContentContainer>
  );
};

NavigationDemoView.propTypes = propTypes;

export default injectIntl(NavigationDemoView);
